# Generated by Django 5.2.7 on 2025-10-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.CharField(choices=[('video', 'Vídeo'), ('pdf', 'Arquivo PDF'), ('zip', 'Arquivo ZIP'), ('link', 'Link'), ('outro', 'Outro')], max_length=10),
        ),
    ]
