# Generated by Django 5.2.7 on 2025-10-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_recurso_tipo_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
